Fix broken AppVeyor build with assertAlmostEqual()
Floating point numbers should always be compared with AlmostEqual!  What
was I thinking?  The resulting broken build:

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.8492/job/vope4rh9s4pgvf2c

was due to a single-digit difference in the least significant place!

```
======================================================================
FAIL: test_hyperbolic_orbit (sgp4.tests.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
AssertionError: Tuples differ: (4.262200676156417, 34.7613408... != (4.262200676156417, 34.7613408...
First differing element 1:
34.76134082028373
34.76134082028372
```